### PR TITLE
Critical fix for $config + Netbeans .gitignore fix

### PR DESCRIPTION
**Pull request by ShadowOfHarbringer**
- Critical fix for $config in constructor 
- Netbeans .gitignore fix for people using netbeans to code

### CODE REVIEW

**Comment by mariuswilms** [comment]
Hi @ShadowOfHarbringer,

Merging of configuration with defaults is correct as-is. Please see http://php.net/manual/en/language.operators.array.php for more information. Missing default values in $config are added not overridden.

**Comment by ShadowOfHarbringer** [comment]
You are merging in the wrong order...

See my example below:

$config = array(
    'persistent'    => 2,
    'host'          => 2,
);

$defaults = [
    'persistent'    => 1,
    'host'          => 1,
];

$bzConfig = $config + $defaults;
Result is:
[
    'persistent'    => 1,
    'host'          => 1,
];

So defaults are ALWAYS taken instead of the config given in parameters... 
This is a serious bug as you cannot really change any parameters.

**Comment by mariuswilms** [comment]
http://sandbox.onlinephpfunctions.com/code/97492df8c0cfdcff8cd647f79ed28217f8176ed0

**Comment by ShadowOfHarbringer** [comment]
OMG that is incredible. Such a stupid "reverse" mistake. Sorry for bothering you.

**Comment by mariuswilms** [comment]
No worries :)

**Pull request closed without merging**
